services:
  - type: web
    name: appsmith
    env: docker
    plan: free
    dockerImage:
      image: appsmith/appsmith-ce
    autoDeploy: true
    disk:
      name: appsmith-data
      mountPath: /appsmith-stacks
      sizeGB: 1
    envVars:
      - key: APPSMITH_MAIL_ENABLED
        value: "false"
      - key: APPSMITH_SIGNUP_DISABLED
        value: "false"
      - key: APPSMITH_DISABLE_TELEMETRY
        value: "false"
      - key: APPSMITH_CUSTOM_DOMAIN
        value: "" # ใส่โดเมนของคุณที่นี่หากมี

