services:
  - type: web
    name: appsmith
    env: docker
    plan: free
    repo: https://github.com/bankwirat/appsmith
    branch: release
    dockerfilePath: ./deploy/docker/Dockerfile
    autoDeploy: true

